# Generated by Django 4.0.4 on 2022-05-12 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0002_producto_descripespecifica'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='ProductosBelleza',
        ),
        migrations.CreateModel(
            name='ProductosSexualidad',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Producto')),
                ('photo_as_blob', models.ImageField(upload_to='farmacia/static/farmacia/img/imagenesDjango', verbose_name='imagen Producto')),
                ('nombreProd', models.CharField(max_length=20, verbose_name='Nombre Producto')),
                ('descripEspecifica', models.CharField(max_length=200, verbose_name='DescripEspecifica')),
                ('unidades', models.CharField(max_length=20, verbose_name='Unidades')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='descripcion')),
                ('price', models.IntegerField(verbose_name='precio')),
                ('IdTipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.tipoproducto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductosMedicamentos',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Producto')),
                ('photo_as_blob', models.ImageField(upload_to='farmacia/static/farmacia/img/imagenesDjango', verbose_name='imagen Producto')),
                ('nombreProd', models.CharField(max_length=20, verbose_name='Nombre Producto')),
                ('descripEspecifica', models.CharField(max_length=200, verbose_name='DescripEspecifica')),
                ('unidades', models.CharField(max_length=20, verbose_name='Unidades')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='descripcion')),
                ('price', models.IntegerField(verbose_name='precio')),
                ('IdTipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.tipoproducto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductosMascotas',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Producto')),
                ('photo_as_blob', models.ImageField(upload_to='farmacia/static/farmacia/img/imagenesDjango', verbose_name='imagen Producto')),
                ('nombreProd', models.CharField(max_length=20, verbose_name='Nombre Producto')),
                ('descripEspecifica', models.CharField(max_length=200, verbose_name='DescripEspecifica')),
                ('unidades', models.CharField(max_length=20, verbose_name='Unidades')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='descripcion')),
                ('price', models.IntegerField(verbose_name='precio')),
                ('IdTipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.tipoproducto')),
            ],
        ),
    ]
