# Generated by Django 4.0.4 on 2022-05-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0005_alter_producto_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idProducto',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id de Producto'),
        ),
    ]
