# Generated by Django 4.0.4 on 2022-05-12 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('idTipo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Tipo Producto')),
                ('nombreTipo', models.CharField(max_length=50, verbose_name='Nombre Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Producto')),
                ('photo_as_blob', models.ImageField(upload_to='farmacia/static/farmacia/img/imagenesDjango', verbose_name='imagen Producto')),
                ('nombreProd', models.CharField(max_length=20, verbose_name='Nombre Producto')),
                ('unidades', models.CharField(max_length=20, verbose_name='Unidades')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='descripcion')),
                ('price', models.IntegerField(verbose_name='precio')),
                ('IdTipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.tipoproducto')),
            ],
        ),
    ]
