# Generated by Django 4.0.4 on 2022-05-12 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0003_rename_producto_productosbelleza_productossexualidad_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductosMedicamentos',
            new_name='Producto',
        ),
        migrations.RemoveField(
            model_name='productosmascotas',
            name='IdTipo',
        ),
        migrations.RemoveField(
            model_name='productossexualidad',
            name='IdTipo',
        ),
        migrations.DeleteModel(
            name='ProductosBelleza',
        ),
        migrations.DeleteModel(
            name='ProductosMascotas',
        ),
        migrations.DeleteModel(
            name='ProductosSexualidad',
        ),
    ]
