# Generated by Django 4.0.5 on 2022-07-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0007_comuna_region_alter_producto_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='stock'),
        ),
    ]
