# Generated by Django 4.0.4 on 2022-07-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0010_alter_historialcompras_fechacompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcompras',
            name='idCompra',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo Compra'),
        ),
    ]
