# Generated by Django 4.0.4 on 2022-07-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0011_alter_historialcompras_idcompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcompras',
            name='fechaCompra',
            field=models.DateTimeField(verbose_name='Fecha Compra'),
        ),
    ]
