# Generated by Django 4.0.4 on 2022-07-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0012_alter_historialcompras_fechacompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcompras',
            name='fechaCompra',
            field=models.DateField(verbose_name='Fecha Compra'),
        ),
    ]
