# Generated by Django 4.0.4 on 2022-07-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0013_alter_historialcompras_fechacompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcompras',
            name='estado',
            field=models.CharField(default='Ordenado', max_length=50, verbose_name='Estado'),
        ),
    ]
