# Generated by Django 4.0.4 on 2022-07-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0015_historialcompras_fechallega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcompras',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=50, verbose_name='Estado'),
        ),
    ]
